<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_payment_jakarta_model extends CI_Model
{

    public $table = 'tbl_payment_jakarta';
    public $id = 'id_payment_jakarta';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->join('tbl_debit_jakarta', 'tbl_debit_jakarta.id_debit_jakarta=tbl_payment_jakarta.id_debit_jakarta');
        $this->db->join('tbl_sub_jakarta', 'tbl_sub_jakarta.id_sub_jakarta=tbl_debit_jakarta.id_sub_jakarta');
        $this->db->join('tbl_spk_jakarta', 'tbl_spk_jakarta.id_spk_jakarta=tbl_sub_jakarta.id_spk_jakarta');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_payment_jakarta', $q);
	$this->db->or_like('id_debit_jakarta', $q);
	$this->db->or_like('jumlah_payment', $q);
	$this->db->or_like('tanggal_payment', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_payment_jakarta', $q);
	$this->db->or_like('id_debit_jakarta', $q);
	$this->db->or_like('jumlah_payment', $q);
	$this->db->or_like('tanggal_payment', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_payment_jakarta_model.php */
/* Location: ./application/models/Tbl_payment_jakarta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2025-12-26 14:29:38 */
/* http://harviacode.com */