<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_vendor_model extends CI_Model
{

    public $table = 'tbl_vendor';
    public $id = 'id_vendor';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_vendor,nama_vendor');
        $this->datatables->from('tbl_vendor');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_vendor.field = table2.field');
        $this->datatables->where('tbl_vendor.hapus', 0);
        $this->datatables->add_column('action', anchor(site_url('tbl_vendor/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('tbl_vendor/delete_sampah/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_vendor');
        
        return $this->datatables->generate();
    }

    function json_sampah() {
        $this->datatables->select('id_vendor,nama_vendor');
        $this->datatables->from('tbl_vendor');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_vendor.field = table2.field');
        $this->datatables->where('tbl_vendor.hapus', 1);
        $this->datatables->add_column('action', anchor(site_url('tbl_vendor/restore_sampah/$1'),'<i class="fa fa-recycle" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('tbl_vendor/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_vendor');
        
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        if($this->uri->segment(2) == 'sampah') {
            $this->db->where('tbl_vendor.hapus', 1);
            
        } else {
            $this->db->where('tbl_vendor.hapus', 0);
            
        }
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        if($this->uri->segment(2) == 'sampah') {
            $this->db->where('tbl_vendor.hapus', 1);
            
        } else {
            $this->db->where('tbl_vendor.hapus', 0);
            
        }
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        if($this->uri->segment(2) == 'sampah') {
            $this->db->where('tbl_vendor.hapus', 1);
            
        } else {
            $this->db->where('tbl_vendor.hapus', 0);
            
        }
        $this->db->like('id_vendor', $q);
        $this->db->or_like('nama_vendor', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        if($this->uri->segment(2) == 'sampah') {
            $this->db->where('tbl_vendor.hapus', 1);
            
        } else {
            $this->db->where('tbl_vendor.hapus', 0);
            
        }
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_vendor', $q);
        $this->db->or_like('nama_vendor', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_vendor_model.php */
/* Location: ./application/models/Tbl_vendor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-02-17 13:43:10 */
/* http://harviacode.com */