<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_pekerjaan_jakarta_model extends CI_Model
{

    public $table = 'tbl_pekerjaan_jakarta';
    public $id = 'id_pekerjaan_jakarta';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_id_read($id) {
        $this->db->select('*, tbl_pekerjaan_jakarta.tgl_stuf, tbl_pekerjaan_jakarta.tgl_selesai_stuf, tbl_pekerjaan_jakarta.etd_kapal, tbl_pekerjaan_jakarta.eta_kapal, tbl_pekerjaan_jakarta.tgl_mulai_doring, tbl_pekerjaan_jakarta.tgl_selesai_doring, tbl_pekerjaan_jakarta.tgl_bap, tbl_pekerjaan_jakarta.jumlah_dikerjakan, tbl_pekerjaan_jakarta.sisa_belum, tbl_pekerjaan_jakarta.status, tbl_pekerjaan_jakarta.keterangan');
		$this->db->join('tbl_sub_jakarta', 'tbl_pekerjaan_jakarta.id_sub_jakarta=tbl_sub_jakarta.id_sub_jakarta');
        $this->db->join('tbl_spk_jakarta', 'tbl_spk_jakarta.id_spk_jakarta=tbl_sub_jakarta.id_spk_jakarta');
        $this->db->where('tbl_pekerjaan_jakarta.id_sub_jakarta', $id);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all_kerja() {
        $this->db->select('*, tbl_pekerjaan_jakarta.tgl_stuf, tbl_pekerjaan_jakarta.tgl_selesai_stuf, tbl_pekerjaan_jakarta.etd_kapal, tbl_pekerjaan_jakarta.eta_kapal, tbl_pekerjaan_jakarta.tgl_mulai_doring, tbl_pekerjaan_jakarta.tgl_selesai_doring, tbl_pekerjaan_jakarta.tgl_bap, tbl_pekerjaan_jakarta.jumlah_dikerjakan, tbl_pekerjaan_jakarta.sisa_belum, tbl_pekerjaan_jakarta.status, tbl_pekerjaan_jakarta.keterangan');
		$this->db->join('tbl_sub_jakarta', 'tbl_pekerjaan_jakarta.id_sub_jakarta=tbl_sub_jakarta.id_sub_jakarta');
        $this->db->join('tbl_spk_jakarta', 'tbl_spk_jakarta.id_spk_jakarta=tbl_sub_jakarta.id_spk_jakarta');

        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_pekerjaan_jakarta', $q);
	$this->db->or_like('id_sub_jakarta', $q);
	$this->db->or_like('tgl_stuf', $q);
	$this->db->or_like('tgl_selesai_stuf', $q);
	$this->db->or_like('etd_kapal', $q);
	$this->db->or_like('eta_kapal', $q);
	$this->db->or_like('tgl_mulai_doring', $q);
	$this->db->or_like('tgl_selesai_doring', $q);
	$this->db->or_like('tgl_bap', $q);
	$this->db->or_like('jumlah_dikerjakan', $q);
	$this->db->or_like('sisa_belum', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_pekerjaan_jakarta', $q);
	$this->db->or_like('id_sub_jakarta', $q);
	$this->db->or_like('tgl_stuf', $q);
	$this->db->or_like('tgl_selesai_stuf', $q);
	$this->db->or_like('etd_kapal', $q);
	$this->db->or_like('eta_kapal', $q);
	$this->db->or_like('tgl_mulai_doring', $q);
	$this->db->or_like('tgl_selesai_doring', $q);
	$this->db->or_like('tgl_bap', $q);
	$this->db->or_like('jumlah_dikerjakan', $q);
	$this->db->or_like('sisa_belum', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_pekerjaan_jakarta_model.php */
/* Location: ./application/models/Tbl_pekerjaan_jakarta_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-01-26 12:39:26 */
/* http://harviacode.com */